AllCops:
  DisplayCopNames: true
  Exclude:
    - "Movies/demo.rb"
    - "Movies/movies.txt"
Metrics/LineLength:
  Max: 240
BlockLength:
  Max: 50
Style/Documentation:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Style/StringLiterals:
  Enabled: false
